
import type { PatientCase } from './types';

export const CASE_DATABASE: PatientCase[] = [
  // --- Cardiology Cases ---
  {
    specialty: 'Cardiology',
    rarity: 'Common',
    demographics: { name: 'David Chen', age: 62, gender: 'Male', occupation: 'Accountant' },
    clinicalBackground: 'Patient has a history of hypertension and hyperlipidemia, smokes half a pack a day.',
    patientHistoryPrompt: "For the last few months, whenever I walk uphill or carry groceries, I get this squeezing feeling in my chest. It's not sharp, more like a heavy pressure. It goes away if I stop and rest for a few minutes. I've also been feeling more tired than usual. My father had heart problems, so I'm getting a bit worried.",
    chiefComplaint: 'Chest tightness with exertion.',
    emotionalState: 'Anxious',
    internalDiagnosis: 'Stable Angina Pectoris',
  },
  {
    specialty: 'Cardiology',
    rarity: 'Uncommon',
    demographics: { name: 'Maria Garcia', age: 34, gender: 'Female', occupation: 'Teacher' },
    clinicalBackground: 'Patient had a recent viral upper respiratory infection about two weeks ago.',
    patientHistoryPrompt: "It started with a really bad cold a couple of weeks back. I thought I was over it, but now I have this sharp, stabbing pain in the center of my chest. It's worse when I breathe in deeply or lie down flat. I feel a bit better if I lean forward. I've also had some fevers and just feel wiped out.",
    chiefComplaint: 'Sharp central chest pain.',
    emotionalState: 'Worried',
    internalDiagnosis: 'Acute Pericarditis',
  },
  {
    specialty: 'Cardiology',
    rarity: 'Rare',
    demographics: { name: 'Brenda Johnson', age: 71, gender: 'Female', occupation: 'Retired' },
    clinicalBackground: 'Patient experienced the recent sudden death of her spouse of 50 years.',
    patientHistoryPrompt: "My husband passed away last week... it's been so hard. A day or two after the funeral, I suddenly felt this overwhelming chest pain and shortness of breath. It felt just like a heart attack. I was so scared. They did tests at the hospital but... I don't know. The pain comes and goes. I just feel so broken.",
    chiefComplaint: 'Sudden onset chest pain and shortness of breath after emotional stress.',
    emotionalState: 'Distraught',
    internalDiagnosis: 'Takotsubo Cardiomyopathy (Broken Heart Syndrome)',
  },
  {
    specialty: 'Cardiology',
    rarity: 'Very Rare',
    demographics: { name: 'Sophia Petrova', age: 28, gender: 'Female', occupation: 'Graphic Designer' },
    clinicalBackground: 'Patient has a known history of Systemic Lupus Erythematosus (SLE), diagnosed 5 years ago.',
    patientHistoryPrompt: "I've been living with Lupus for a while, but this is new. I'm getting out of breath just walking to the kitchen. My feet have been really swollen, and I've been having these weird fevers. Sometimes I can feel my heart pounding in a strange way. My joints are flaring up more than usual too. I just feel awful all over.",
    chiefComplaint: 'Progressive shortness of breath and swollen ankles.',
    emotionalState: 'Fatigued',
    internalDiagnosis: 'Libman-Sacks Endocarditis secondary to SLE',
  },

  // --- Neurology Cases ---
  {
    specialty: 'Neurology',
    rarity: 'Common',
    demographics: { name: 'Kevin Lee', age: 25, gender: 'Male', occupation: 'Software Developer' },
    clinicalBackground: 'Patient reports increased work stress and screen time. There is a family history of migraines.',
    patientHistoryPrompt: "About an hour before the headache starts, I see these shimmering, wavy lines in my vision, almost like heat haze. It makes it hard to focus on my screen. Then, this throbbing pain starts, usually on the right side of my head. I get really sensitive to light and noise, and sometimes I feel nauseous. I just have to go lie down in a dark, quiet room until it passes.",
    chiefComplaint: 'Throbbing headache with visual disturbances.',
    emotionalState: 'Frustrated',
    internalDiagnosis: 'Migraine with Aura',
  },
  {
    specialty: 'Neurology',
    rarity: 'Uncommon',
    demographics: { name: 'Fatima Al-Jamil', age: 45, gender: 'Female', occupation: 'Chef' },
    clinicalBackground: 'No significant prior medical history. Patient reports things tasting "off" recently.',
    patientHistoryPrompt: "I woke up yesterday morning and the left side of my face just felt... weird. When I looked in the mirror, it was drooping. I can't seem to close my left eye properly, and my smile is all lopsided. It's really embarrassing. Food also tastes strange, and everything sounds really loud in my left ear. I was so scared I was having a stroke.",
    chiefComplaint: 'Sudden weakness of one side of the face.',
    emotionalState: 'Scared',
    internalDiagnosis: "Bell's Palsy",
  },
  {
    specialty: 'Neurology',
    rarity: 'Rare',
    demographics: { name: 'George Miller', age: 58, gender: 'Male', occupation: 'Construction Worker' },
    clinicalBackground: 'Patient had a bout of gastroenteritis (stomach flu) about three weeks prior to symptom onset.',
    patientHistoryPrompt: "It started in my feet a couple of weeks ago, this weird tingling, pins-and-needles feeling. I thought I'd just pinched a nerve. But then the tingling spread up my legs, and they started to feel really weak. Now it's in my arms and hands too. It's getting harder to walk or even hold a coffee cup. I've never felt anything like this. I feel like my body is failing me from the ground up.",
    chiefComplaint: 'Ascending weakness and tingling in limbs.',
    emotionalState: 'Fearful',
    internalDiagnosis: 'Guillain-Barré Syndrome (GBS)',
  },
  {
    specialty: 'Neurology',
    rarity: 'Very Rare',
    demographics: { name: 'Eleanor Vance', age: 67, gender: 'Female', occupation: 'Librarian' },
    clinicalBackground: 'Patient\'s family reports rapid cognitive decline and new, jerky movements.',
    patientHistoryPrompt: "My family brought me here. They say I've been... different. Forgetting things, not just keys, but whole conversations. I feel confused a lot. My balance is off, I stumble sometimes. And my hands... they sometimes just jerk on their own, I can't control it. It's all happened so fast, just in the last couple of months. It feels like my mind is slipping away from me.",
    chiefComplaint: 'Rapidly progressive memory loss and involuntary movements.',
    emotionalState: 'Confused',
    internalDiagnosis: 'Creutzfeldt-Jakob Disease (CJD)',
  },

  // --- Gastroenterology Cases ---
  {
    specialty: 'Gastroenterology',
    rarity: 'Common',
    demographics: { name: 'Susan White', age: 48, gender: 'Female', occupation: 'Sales Manager' },
    clinicalBackground: 'Patient reports frequent use of NSAIDs for headaches and enjoys spicy food and coffee.',
    patientHistoryPrompt: "For the past year, I've been getting this awful burning feeling in my chest, right behind my breastbone. It's usually worse after a big meal, especially if I lie down. Sometimes I wake up at night choking on this sour, acidic taste in my mouth. I've been taking a lot of antacids, and they help a little, but it keeps coming back. It's really starting to affect my sleep.",
    chiefComplaint: 'Burning chest pain, worse after meals.',
    emotionalState: 'Tired',
    internalDiagnosis: 'Gastroesophageal Reflux Disease (GERD)',
  },
  {
    specialty: 'Gastroenterology',
    rarity: 'Uncommon',
    demographics: { name: 'Liam O\'Connell', age: 31, gender: 'Male', occupation: 'Student' },
    clinicalBackground: 'Patient has a history of iron deficiency anemia with no obvious source of bleeding.',
    patientHistoryPrompt: "I just feel drained all the time. I'm bloated and gassy no matter what I eat. I've been losing weight without trying to. I also get these weird, itchy rashes on my elbows and knees. My doctor said I was anemic, but the iron pills just upset my stomach. I feel like my body isn't absorbing any nutrients. It's been going on for years, but it's getting worse.",
    chiefComplaint: 'Chronic fatigue, bloating, and unexplained weight loss.',
    emotionalState: 'Frustrated',
    internalDiagnosis: 'Celiac Disease',
  },
  {
    specialty: 'Gastroenterology',
    rarity: 'Rare',
    demographics: { name: 'Daniel Chen', age: 22, gender: 'Male', occupation: 'University Student' },
    clinicalBackground: 'Patient\'s university health services noted abnormal liver function tests. Family has noticed slight personality changes.',
    patientHistoryPrompt: "I've been feeling... off. My friends say I've been more moody and impulsive lately. I've also noticed my hands have a bit of a tremor when I hold them out. The weirdest thing is, I think my eyes look strange. Someone pointed out these brownish rings around the colored part of my eyes. I've also had some belly pain and my skin looks a little yellow.",
    chiefComplaint: 'Mood changes, hand tremor, and yellowish skin.',
    emotionalState: 'Anxious',
    internalDiagnosis: "Wilson's Disease",
  },
  {
    specialty: 'Gastroenterology',
    rarity: 'Very Rare',
    demographics: { name: 'Arthur Finch', age: 55, gender: 'Male', occupation: 'Farmer' },
    clinicalBackground: 'A middle-aged man with a multi-systemic illness.',
    patientHistoryPrompt: "Doctor, I feel like I'm falling apart. It started with my joints aching, especially my knees and back. Then I started losing a lot of weight because of constant diarrhea. My belly is always cramping. I'm so tired I can barely work on the farm. My memory has gotten foggy, and sometimes my eyes get all blurry and twitch. It's been a slow, downhill slide for the last year.",
    chiefComplaint: 'Joint pain, chronic diarrhea, and weight loss.',
    emotionalState: 'Depressed',
    internalDiagnosis: "Whipple's Disease",
  },

  // --- Pulmonology Cases ---
  {
    specialty: 'Pulmonology',
    rarity: 'Common',
    demographics: { name: 'Robert Smith', age: 68, gender: 'Male', occupation: 'Retired Smoker' },
    clinicalBackground: 'Patient is a long-term smoker with a history of COPD.',
    patientHistoryPrompt: "I've had a smoker's cough for years, but this is different. For the past week, I've been coughing up this thick, yellow-green stuff. I'm running a fever, getting chills, and I feel weaker than a kitten. It hurts to take a deep breath, like a sharp pain in the right side of my chest. I'm so much more breathless than my usual.",
    chiefComplaint: 'Fever, productive cough, and chest pain.',
    emotionalState: 'Ill',
    internalDiagnosis: 'Community-Acquired Pneumonia',
  },
  {
    specialty: 'Pulmonology',
    rarity: 'Uncommon',
    demographics: { name: 'Aisha Jones', age: 39, gender: 'Female', occupation: 'Social Worker' },
    clinicalBackground: 'Patient is an African American female presenting with a persistent dry cough.',
    patientHistoryPrompt: "For months, I've had this nagging, dry cough that just won't go away. I'm also really tired all the time, and I've been having some fevers at night. I've also noticed these tender, red bumps on my shins. It's just a general feeling of being unwell that I can't shake. The cough is the most annoying part, it's there day and night.",
    chiefComplaint: 'Persistent dry cough and fatigue for several months.',
    emotionalState: 'Weary',
    internalDiagnosis: 'Sarcoidosis',
  },
  {
    specialty: 'Pulmonology',
    rarity: 'Rare',
    demographics: { name: 'Jessica Davis', age: 29, gender: 'Female', occupation: 'Architect' },
    clinicalBackground: 'Patient has a history of recurrent chest infections and was told she had "asthma" as a child, but inhalers never fully helped.',
    patientHistoryPrompt: "All my life, I've had chest problems. I get bronchitis or pneumonia at least twice a year. I have this chronic, wet cough and I'm always trying to clear my throat. Doctors always said it was asthma, but it feels like more than that. I also have trouble digesting my food properly; I get a lot of stomach pain and greasy stools. It's really hard to keep my weight up.",
    chiefComplaint: 'Recurrent chest infections and digestive issues.',
    emotionalState: 'Resigned',
    internalDiagnosis: 'Cystic Fibrosis (Atypical/Adult Presentation)',
  },
  {
    specialty: 'Pulmonology',
    rarity: 'Very Rare',
    demographics: { name: 'Ben Carter', age: 42, gender: 'Male', occupation: 'Historian' },
    clinicalBackground: 'Patient has a lifelong history of sinus and ear infections. He and his partner have been unable to conceive.',
    patientHistoryPrompt: "Ever since I was a kid, I've been sick. Constant sinus infections, ear infections, and a cough that never, ever goes away. I'm always congested. The doctors call it 'bronchiectasis'. My wife and I have also been trying for a baby for years with no luck. It's a lot to deal with. I just want to know why my body seems to have such a hard time with simple infections.",
    chiefComplaint: 'Lifelong history of sino-pulmonary infections and infertility.',
    emotionalState: 'Frustrated',
    internalDiagnosis: 'Primary Ciliary Dyskinesia (Kartagener Syndrome)',
  },

  // --- Infectious Disease Cases ---
  {
    specialty: 'Infectious Disease',
    rarity: 'Common',
    demographics: { name: 'Chloe Kim', age: 19, gender: 'Female', occupation: 'College Student' },
    clinicalBackground: 'Patient lives in a college dormitory and reports sharing drinks with friends recently.',
    patientHistoryPrompt: "I've never felt this tired in my entire life. It's a bone-deep exhaustion that sleep doesn't fix. It started a week ago with a really sore throat – it felt like swallowing glass – and a fever. My neck feels swollen and tender. I just want to sleep all day. I can barely keep up with my classes.",
    chiefComplaint: 'Extreme fatigue, sore throat, and fever.',
    emotionalState: 'Exhausted',
    internalDiagnosis: 'Infectious Mononucleosis',
  },
  {
    specialty: 'Infectious Disease',
    rarity: 'Uncommon',
    demographics: { name: 'Tom Harding', age: 41, gender: 'Male', occupation: 'Park Ranger' },
    clinicalBackground: 'Patient works outdoors in the Northeastern US and recalls being bitten by a tick about a month ago.',
    patientHistoryPrompt: "About a month ago, I had this weird circular rash on my leg, looked like a bullseye, but it went away. I didn't think much of it. But for the last couple of weeks, I've been feeling awful. My joints, especially my knees, are so achy and swollen. I get headaches, feel dizzy, and my whole body just hurts. It feels like a bad flu that I can't shake.",
    chiefComplaint: 'Joint pain, headache, and fatigue after a rash.',
    emotionalState: 'Achy',
    internalDiagnosis: 'Lyme Disease',
  },
  {
    specialty: 'Infectious Disease',
    rarity: 'Rare',
    demographics: { name: 'Isabelle Rossi', age: 33, gender: 'Female', occupation: 'Travel Blogger' },
    clinicalBackground: 'Patient recently returned from a two-week trip to Southeast Asia.',
    patientHistoryPrompt: "I just got back from Thailand a few days ago and I feel terrible. I have a really high fever, a splitting headache behind my eyes, and my whole body aches. My muscles, my bones, everything hurts. I also have this faint red rash across my chest and back. I've never felt so sick. I'm worried I caught something serious over there.",
    chiefComplaint: 'High fever, severe headache, and body aches after international travel.',
    emotionalState: 'Miserable',
    internalDiagnosis: 'Dengue Fever',
  },
  {
    specialty: 'Infectious Disease',
    rarity: 'Very Rare',
    demographics: { name: 'Peter O\'Malley', age: 65, gender: 'Male', occupation: 'Retired Gardener with Diabetes' },
    clinicalBackground: 'Patient with type 2 diabetes lives in a tropical region (e.g., Northern Australia) and has a non-healing ulcer on his foot.',
    patientHistoryPrompt: "I have this cut on my foot from gardening that just won't heal. It's been weeks. Now, for the past few days, I've been really sick. High fevers, sweats, and I'm coughing up a storm. It hurts in my chest to breathe. I feel confused and just generally very unwell. My diabetes has been hard to control with this sickness. I feel like I have a really bad case of pneumonia.",
    chiefComplaint: 'Fever and productive cough in a diabetic patient with a non-healing skin ulcer.',
    emotionalState: 'Septic',
    internalDiagnosis: 'Melioidosis',
  },
];
